# Generated by Django 5.0.2 on 2024-02-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_blogmodel_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='category',
            field=models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('other', 'Other'), ('testing', 'Testing')], max_length=20),
        ),
    ]
