# Generated by Django 5.0.2 on 2024-02-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_blogmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='category',
            field=models.CharField(choices=[('HW', 'Hardware'), ('SW', 'Software'), ('B', 'Benchmarks'), ('MISC', 'Miscellaneous')], max_length=20),
        ),
    ]
