# Generated by Django 5.0.2 on 2024-02-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_blogmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
