# Generated by Django 5.0.2 on 2024-02-26 13:43

import blog_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_blogmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='images',
            field=models.ImageField(null=True, upload_to=blog_app.models.getFileName),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='main_img',
            field=models.ImageField(default='default.png', upload_to=blog_app.models.getFileName),
        ),
    ]
