# Generated by Django 5.0.2 on 2024-02-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_blogmodel_images_blogmodel_main_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='images',
        ),
    ]
