# Generated by Django 5.0.2 on 2024-05-09 10:30

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_blogmodel_slug_alter_blogmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='text',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
