# Generated by Django 5.0.2 on 2024-05-09 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_alter_blogmodel_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
