# Generated by Django 5.0.2 on 2024-05-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0014_alter_blogmodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='last_edit',
            field=models.DateTimeField(null=True),
        ),
    ]
