# Generated by Django 5.0.2 on 2024-05-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_blogmodel_last_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='last_edit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
