# Generated by Django 5.0.2 on 2024-05-15 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0017_commentsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodel',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog_app.blogmodel'),
        ),
    ]
